.TH "onload" "1" "onload man page" "onload" ""
.hy
.SH NAME
.PP
\f[B]onload\f[R] \- command line system information tool
.SH DESCRIPTION
.PP
Displays basic system information to stdout and configure settings
through headers.
.SH FILES
.PP
\f[I]main.c\f[R] provided for convenience

\f[I]include/onload/onload.h\f[R] configuration for outputing results

\f[I]include/colourbar/colourbar.h\f[R] configuration for customizing
colourbar

.SH AUTHOR
.PP
Xander Tedder <xandertedder7@gmail.com>
.SH SEE ALSO
.PP
\f[B]onload(1)\f[R]
